#!/bin/bash

# System Report generated by USERNAME, DATE/TIME
echo "System Report generated by $(whoami), $(date)"

# System Information
echo "System Information"
echo "------------------"
echo "Hostname: $(hostname)"
echo "OS: $(lsb_release -d | cut -f2)"
echo "Uptime: $(uptime -p)"

# Hardware Information
echo "Hardware Information"
echo "--------------------"
echo "CPU: $(lshw -class processor | grep 'product:' | head -n 1 | cut -d: -f2 | xargs)"
echo "RAM: $(free -h | grep Mem | awk '{print $2}')"
echo "Disk(s): $(lsblk -o NAME,SIZE,MODEL | grep -v loop | grep -v sr0)"

# Network Information
echo "Network Information"
echo "-------------------"
echo "FQDN: $(hostname -f)"
echo "Host Address: $(hostname -I | awk '{print $1}')"
echo "Gateway IP: $(ip route | grep default | awk '{print $3}')"

# System Status
echo "System Status"
echo "-------------"
echo "Users Logged In: $(who | awk '{print $1}' | sort | uniq | tr '\n' ',')"
echo "Process Count: $(ps aux | wc -l)"
echo "Load Averages: $(cat /proc/loadavg | awk '{print $1, $2, $3}')"

